#ifndef SIMULATEUR
#define SIMULATEUR

//Mettre le code ici
//fonction aiguillage purgatoire
void AiguillagePurgatoire (PPF *,COURS_ALGO **,COURS_ALGO *,FILE_POSTE **,FILE_POSTE*,EPILATION_CHEVEUX **,EPILATION_CHEVEUX *,MARSEILLAIS **,MARSEILLAIS *,int );
void simulation(PPF **,COURS_ALGO **,FILE_POSTE **,EPILATION_CHEVEUX **,MARSEILLAIS **,PPF *,COURS_ALGO *,FILE_POSTE *,EPILATION_CHEVEUX *,MARSEILLAIS *);
void simulationSed(PPF **,COURS_ALGO **,FILE_POSTE **,EPILATION_CHEVEUX **,MARSEILLAIS **,PPF *,COURS_ALGO *,FILE_POSTE *,EPILATION_CHEVEUX *,MARSEILLAIS *,ECH *, EVT*);
void update(PPF **,COURS_ALGO **,FILE_POSTE **,EPILATION_CHEVEUX **,MARSEILLAIS **,PPF *,COURS_ALGO *,FILE_POSTE *,EPILATION_CHEVEUX *,MARSEILLAIS *);
void updatecompteur(COURS_ALGO *, FILE_POSTE *,EPILATION_CHEVEUX *,MARSEILLAIS *);
COURS_ALGO* copieListeFrag(COURS_ALGO *);
void Affichageapresupdate(COURS_ALGO *, FILE_POSTE *, EPILATION_CHEVEUX *, MARSEILLAIS *);
void AiguillagePurgatoireSed(PPF *,ECH *, EVT *, int);



#endif
